name: moniepoint_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  google_maps_flutter: ^2.8.0
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
  
  fonts:
    - family: EuclidCircularA
      fonts:
        - asset: assets/fonts/EuclidCircularA-Light.ttf
        - asset: assets/fonts/EuclidCircularA-LightItalic.ttf
        - asset: assets/fonts/EuclidCircularA-Regular.ttf
        - asset: assets/fonts/EuclidCircularA-Italic.ttf
        - asset: assets/fonts/EuclidCircularA-Medium.ttf
        - asset: assets/fonts/EuclidCircularA-MediumItalic.ttf
        - asset: assets/fonts/EuclidCircularA-Bold.ttf
        - asset: assets/fonts/EuclidCircularA-BoldItalic.ttf
        - asset: assets/fonts/EuclidCircularA-SemiBold.ttf
        - asset: assets/fonts/EuclidCircularA-SemiBoldItalic.ttf
