name: moniepoint_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_svg: ^2.0.10+1
  google_maps_flutter: ^2.6.0
  iconsax: ^0.0.8
  latlong2: ^0.9.1

dependency_overrides:
    flutter_map:
        git:
            url: https://github.com/fleaflet/flutter_map.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
  
  fonts:
    - family: EuclidCircularA
      fonts:
        - asset: assets/fonts/EuclidCircularA-Light.ttf
        - asset: assets/fonts/EuclidCircularA-LightItalic.ttf
        - asset: assets/fonts/EuclidCircularA-Regular.ttf
        - asset: assets/fonts/EuclidCircularA-Italic.ttf
        - asset: assets/fonts/EuclidCircularA-Medium.ttf
        - asset: assets/fonts/EuclidCircularA-MediumItalic.ttf
        - asset: assets/fonts/EuclidCircularA-Bold.ttf
        - asset: assets/fonts/EuclidCircularA-BoldItalic.ttf
        - asset: assets/fonts/EuclidCircularA-SemiBold.ttf
        - asset: assets/fonts/EuclidCircularA-SemiBoldItalic.ttf
